apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.7.03
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.03
    spec:
      containers:
      - name: myjavaapp-container
        image: maha4iac/mymahalogin:3
        ports:
        - containerPort: 8080